kind: pipeline
type: docker
name: integration

trigger: 
  branch:
    - master
  event:
    exclude:
      - pull_request
steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarQubeSecret
    commands:
      - dotnet sonarscanner begin 
          /k:"easv-devops_Climate_AY7hF_zMEVvRW2O60EsK" 
          /d:sonar.host.url="http://sonar.setgo.dk:9000" 
          /d:sonar.token="$SONARSECRET"
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          /d:sonar.qualitygate.wait=true
      - dotnet build api/api.csproj --no-incremental
      - dotnet-coverage collect "dotnet test tests/tests.csproj" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"

---

kind: pipeline
type: docker
name: deliver
trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
depends_on:
  - integration

steps:
  - name: publish api
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      dockerfile: api/Dockerfile
      repo: midr/climate-backend
      tags:
        - staging

  - name: publish web
    image: plugins/docker
    settings:
      username:
        from_secret: DockerUsername
      password:
        from_secret: DockerPassword
      dockerfile: frontend/Dockerfile
      repo: midr/climate-frontend
      tags:
        - staging

  - name: trigger update
    image: curlimages/curl
    environment:
      TOKEN:
        from_secret: WatchtowerToken
    commands:
      # Must match the token defined in docker-compose.yml
      - "curl --fail -X GET 'http://4.231.252.47:8080/v1/update' -H 'Authorization: Bearer $TOKEN'"
      - sleep 10
    depends_on:
      - publish api
      - publish web

  - name: update database
    image: flyway/flyway
    environment:
      DB_URL:
        from_secret: DBUrlSecret
      DB_USER:
        from_secret: DBUserSecret
      DB_PASSWORD:
        from_secret: DBPasswordSecret
    commands:
      - flyway migrate
        -url="$DB_URL"
        -user="$DB_USER"
        -password="$DB_PASSWORD"
        -locations=filesystem:./db/sql
    depends_on:
      - trigger update

  - name: performance tests
    image: grafana/k6
    commands:
      - k6 run tests/performance/spike.js
    depends_on:
      - update database