
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DBNameSecret}
      MYSQL_USER: ${DBUserSecret}
      MYSQL_PASSWORD: ${DBPasswordSecret}
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=mytoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080

volumes:
  mariadb: